### ISSUE TITLE
Update docs for `get_text` to point to `fs::read_to_string`

### ISSUE THREAD

**Issue by matklad** [pornel/rust-file#4]
Wow, looks like we've got one-liner to read a text file in std in 1.26!

https://doc.rust-lang.org/beta/std/fs/fn.read_to_string.html

we should point that out in the docs.

**Comment by matklad** [comment]
Hm, probably all docs have to be updated, and the crate can be effectively deprecated for Rust post 1.26.0, yay!

https://doc.rust-lang.org/beta/std/fs/fn.read.html
https://doc.rust-lang.org/beta/std/fs/fn.write.html
https://doc.rust-lang.org/beta/std/fs/fn.read_to_string.html
`write_string` is just `write` I think?

**Comment by kornelski** [comment]
Yes, it looks like it.
